// This file is automatically generated. Do not edit it directly.
// Updated to use custom API backend instead of Supabase

// Import auth service that connects to our API
import { supabase as authService } from '@/services/auth.service';

// Re-export the auth service as supabase for backward compatibility
export const supabase = authService;

// Legacy Supabase client configuration (kept for reference)
// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;